apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: jupyter-sa
  namespace: jupyter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: jupyter-role
  namespace: jupyter
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: jupyter-rolebinding
  namespace: jupyter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jupyter-role
subjects:
- kind: ServiceAccount
  name: jupyter-sa
  namespace: jupyter
